apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitops-api
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  namespaceSelector:
    matchNames:
      - three-tier
  selector:
    matchLabels:
      app: gitops-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s